* Fixed NoSuchMethodError on STBImageResize.nstbir_resize_uint8 error * Fixed GL_INVALID_ENUM error * Added .gitignore * Added ClientRenderEvent * Added GameRendererMixin ClientRenderEvent post section * AimAssistModule slight consept refactor to be ClientRender based and not tick based making the rotations seem smoother.give me a title out of this for pull request